// Code generated by capnpc-go. DO NOT EDIT.

package vmdaemon

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type VmDaemon capnp.Client

// VmDaemon_TypeID is the unique identifier for the type VmDaemon.
const VmDaemon_TypeID = 0x85dcd3342469e47f

func (c VmDaemon) SpawnGrain(ctx context.Context, params func(VmDaemon_spawnGrain_Params) error) (VmDaemon_spawnGrain_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x85dcd3342469e47f,
			MethodID:      0,
			InterfaceName: "vmdaemon.capnp:VmDaemon",
			MethodName:    "spawnGrain",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 3}
		s.PlaceArgs = func(s capnp.Struct) error { return params(VmDaemon_spawnGrain_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return VmDaemon_spawnGrain_Results_Future{Future: ans.Future()}, release

}

func (c VmDaemon) KillGrain(ctx context.Context, params func(VmDaemon_killGrain_Params) error) (VmDaemon_killGrain_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x85dcd3342469e47f,
			MethodID:      1,
			InterfaceName: "vmdaemon.capnp:VmDaemon",
			MethodName:    "killGrain",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(VmDaemon_killGrain_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return VmDaemon_killGrain_Results_Future{Future: ans.Future()}, release

}

func (c VmDaemon) ListGrains(ctx context.Context, params func(VmDaemon_listGrains_Params) error) (VmDaemon_listGrains_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x85dcd3342469e47f,
			MethodID:      2,
			InterfaceName: "vmdaemon.capnp:VmDaemon",
			MethodName:    "listGrains",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(VmDaemon_listGrains_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return VmDaemon_listGrains_Results_Future{Future: ans.Future()}, release

}

func (c VmDaemon) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c VmDaemon) String() string {
	return "VmDaemon(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c VmDaemon) AddRef() VmDaemon {
	return VmDaemon(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c VmDaemon) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c VmDaemon) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c VmDaemon) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (VmDaemon) DecodeFromPtr(p capnp.Ptr) VmDaemon {
	return VmDaemon(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c VmDaemon) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c VmDaemon) IsSame(other VmDaemon) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c VmDaemon) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c VmDaemon) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A VmDaemon_Server is a VmDaemon with a local implementation.
type VmDaemon_Server interface {
	SpawnGrain(context.Context, VmDaemon_spawnGrain) error

	KillGrain(context.Context, VmDaemon_killGrain) error

	ListGrains(context.Context, VmDaemon_listGrains) error
}

// VmDaemon_NewServer creates a new Server from an implementation of VmDaemon_Server.
func VmDaemon_NewServer(s VmDaemon_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(VmDaemon_Methods(nil, s), s, c)
}

// VmDaemon_ServerToClient creates a new Client from an implementation of VmDaemon_Server.
// The caller is responsible for calling Release on the returned Client.
func VmDaemon_ServerToClient(s VmDaemon_Server) VmDaemon {
	return VmDaemon(capnp.NewClient(VmDaemon_NewServer(s)))
}

// VmDaemon_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func VmDaemon_Methods(methods []server.Method, s VmDaemon_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x85dcd3342469e47f,
			MethodID:      0,
			InterfaceName: "vmdaemon.capnp:VmDaemon",
			MethodName:    "spawnGrain",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.SpawnGrain(ctx, VmDaemon_spawnGrain{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x85dcd3342469e47f,
			MethodID:      1,
			InterfaceName: "vmdaemon.capnp:VmDaemon",
			MethodName:    "killGrain",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.KillGrain(ctx, VmDaemon_killGrain{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x85dcd3342469e47f,
			MethodID:      2,
			InterfaceName: "vmdaemon.capnp:VmDaemon",
			MethodName:    "listGrains",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ListGrains(ctx, VmDaemon_listGrains{call})
		},
	})

	return methods
}

// VmDaemon_spawnGrain holds the state for a server call to VmDaemon.spawnGrain.
// See server.Call for documentation.
type VmDaemon_spawnGrain struct {
	*server.Call
}

// Args returns the call's arguments.
func (c VmDaemon_spawnGrain) Args() VmDaemon_spawnGrain_Params {
	return VmDaemon_spawnGrain_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c VmDaemon_spawnGrain) AllocResults() (VmDaemon_spawnGrain_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return VmDaemon_spawnGrain_Results(r), err
}

// VmDaemon_killGrain holds the state for a server call to VmDaemon.killGrain.
// See server.Call for documentation.
type VmDaemon_killGrain struct {
	*server.Call
}

// Args returns the call's arguments.
func (c VmDaemon_killGrain) Args() VmDaemon_killGrain_Params {
	return VmDaemon_killGrain_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c VmDaemon_killGrain) AllocResults() (VmDaemon_killGrain_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return VmDaemon_killGrain_Results(r), err
}

// VmDaemon_listGrains holds the state for a server call to VmDaemon.listGrains.
// See server.Call for documentation.
type VmDaemon_listGrains struct {
	*server.Call
}

// Args returns the call's arguments.
func (c VmDaemon_listGrains) Args() VmDaemon_listGrains_Params {
	return VmDaemon_listGrains_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c VmDaemon_listGrains) AllocResults() (VmDaemon_listGrains_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VmDaemon_listGrains_Results(r), err
}

// VmDaemon_List is a list of VmDaemon.
type VmDaemon_List = capnp.CapList[VmDaemon]

// NewVmDaemon_List creates a new list of VmDaemon.
func NewVmDaemon_List(s *capnp.Segment, sz int32) (VmDaemon_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[VmDaemon](l), err
}

type VmDaemon_spawnGrain_Params capnp.Struct

// VmDaemon_spawnGrain_Params_TypeID is the unique identifier for the type VmDaemon_spawnGrain_Params.
const VmDaemon_spawnGrain_Params_TypeID = 0xd8dc60b8c4112fc9

func NewVmDaemon_spawnGrain_Params(s *capnp.Segment) (VmDaemon_spawnGrain_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return VmDaemon_spawnGrain_Params(st), err
}

func NewRootVmDaemon_spawnGrain_Params(s *capnp.Segment) (VmDaemon_spawnGrain_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return VmDaemon_spawnGrain_Params(st), err
}

func ReadRootVmDaemon_spawnGrain_Params(msg *capnp.Message) (VmDaemon_spawnGrain_Params, error) {
	root, err := msg.Root()
	return VmDaemon_spawnGrain_Params(root.Struct()), err
}

func (s VmDaemon_spawnGrain_Params) String() string {
	str, _ := text.Marshal(0xd8dc60b8c4112fc9, capnp.Struct(s))
	return str
}

func (s VmDaemon_spawnGrain_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VmDaemon_spawnGrain_Params) DecodeFromPtr(p capnp.Ptr) VmDaemon_spawnGrain_Params {
	return VmDaemon_spawnGrain_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VmDaemon_spawnGrain_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VmDaemon_spawnGrain_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VmDaemon_spawnGrain_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VmDaemon_spawnGrain_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VmDaemon_spawnGrain_Params) PackageId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s VmDaemon_spawnGrain_Params) HasPackageId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s VmDaemon_spawnGrain_Params) PackageIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s VmDaemon_spawnGrain_Params) SetPackageId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s VmDaemon_spawnGrain_Params) GrainId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s VmDaemon_spawnGrain_Params) HasGrainId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s VmDaemon_spawnGrain_Params) GrainIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s VmDaemon_spawnGrain_Params) SetGrainId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s VmDaemon_spawnGrain_Params) Args() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s VmDaemon_spawnGrain_Params) HasArgs() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s VmDaemon_spawnGrain_Params) SetArgs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewArgs sets the args field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s VmDaemon_spawnGrain_Params) NewArgs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// VmDaemon_spawnGrain_Params_List is a list of VmDaemon_spawnGrain_Params.
type VmDaemon_spawnGrain_Params_List = capnp.StructList[VmDaemon_spawnGrain_Params]

// NewVmDaemon_spawnGrain_Params creates a new list of VmDaemon_spawnGrain_Params.
func NewVmDaemon_spawnGrain_Params_List(s *capnp.Segment, sz int32) (VmDaemon_spawnGrain_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[VmDaemon_spawnGrain_Params](l), err
}

// VmDaemon_spawnGrain_Params_Future is a wrapper for a VmDaemon_spawnGrain_Params promised by a client call.
type VmDaemon_spawnGrain_Params_Future struct{ *capnp.Future }

func (f VmDaemon_spawnGrain_Params_Future) Struct() (VmDaemon_spawnGrain_Params, error) {
	p, err := f.Future.Ptr()
	return VmDaemon_spawnGrain_Params(p.Struct()), err
}

type VmDaemon_spawnGrain_Results capnp.Struct

// VmDaemon_spawnGrain_Results_TypeID is the unique identifier for the type VmDaemon_spawnGrain_Results.
const VmDaemon_spawnGrain_Results_TypeID = 0x95f8c5e38213da84

func NewVmDaemon_spawnGrain_Results(s *capnp.Segment) (VmDaemon_spawnGrain_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return VmDaemon_spawnGrain_Results(st), err
}

func NewRootVmDaemon_spawnGrain_Results(s *capnp.Segment) (VmDaemon_spawnGrain_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return VmDaemon_spawnGrain_Results(st), err
}

func ReadRootVmDaemon_spawnGrain_Results(msg *capnp.Message) (VmDaemon_spawnGrain_Results, error) {
	root, err := msg.Root()
	return VmDaemon_spawnGrain_Results(root.Struct()), err
}

func (s VmDaemon_spawnGrain_Results) String() string {
	str, _ := text.Marshal(0x95f8c5e38213da84, capnp.Struct(s))
	return str
}

func (s VmDaemon_spawnGrain_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VmDaemon_spawnGrain_Results) DecodeFromPtr(p capnp.Ptr) VmDaemon_spawnGrain_Results {
	return VmDaemon_spawnGrain_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VmDaemon_spawnGrain_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VmDaemon_spawnGrain_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VmDaemon_spawnGrain_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VmDaemon_spawnGrain_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VmDaemon_spawnGrain_Results) VsockPort() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s VmDaemon_spawnGrain_Results) SetVsockPort(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// VmDaemon_spawnGrain_Results_List is a list of VmDaemon_spawnGrain_Results.
type VmDaemon_spawnGrain_Results_List = capnp.StructList[VmDaemon_spawnGrain_Results]

// NewVmDaemon_spawnGrain_Results creates a new list of VmDaemon_spawnGrain_Results.
func NewVmDaemon_spawnGrain_Results_List(s *capnp.Segment, sz int32) (VmDaemon_spawnGrain_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[VmDaemon_spawnGrain_Results](l), err
}

// VmDaemon_spawnGrain_Results_Future is a wrapper for a VmDaemon_spawnGrain_Results promised by a client call.
type VmDaemon_spawnGrain_Results_Future struct{ *capnp.Future }

func (f VmDaemon_spawnGrain_Results_Future) Struct() (VmDaemon_spawnGrain_Results, error) {
	p, err := f.Future.Ptr()
	return VmDaemon_spawnGrain_Results(p.Struct()), err
}

type VmDaemon_killGrain_Params capnp.Struct

// VmDaemon_killGrain_Params_TypeID is the unique identifier for the type VmDaemon_killGrain_Params.
const VmDaemon_killGrain_Params_TypeID = 0xacf36c3686aaaf17

func NewVmDaemon_killGrain_Params(s *capnp.Segment) (VmDaemon_killGrain_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VmDaemon_killGrain_Params(st), err
}

func NewRootVmDaemon_killGrain_Params(s *capnp.Segment) (VmDaemon_killGrain_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VmDaemon_killGrain_Params(st), err
}

func ReadRootVmDaemon_killGrain_Params(msg *capnp.Message) (VmDaemon_killGrain_Params, error) {
	root, err := msg.Root()
	return VmDaemon_killGrain_Params(root.Struct()), err
}

func (s VmDaemon_killGrain_Params) String() string {
	str, _ := text.Marshal(0xacf36c3686aaaf17, capnp.Struct(s))
	return str
}

func (s VmDaemon_killGrain_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VmDaemon_killGrain_Params) DecodeFromPtr(p capnp.Ptr) VmDaemon_killGrain_Params {
	return VmDaemon_killGrain_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VmDaemon_killGrain_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VmDaemon_killGrain_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VmDaemon_killGrain_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VmDaemon_killGrain_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VmDaemon_killGrain_Params) GrainId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s VmDaemon_killGrain_Params) HasGrainId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s VmDaemon_killGrain_Params) GrainIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s VmDaemon_killGrain_Params) SetGrainId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// VmDaemon_killGrain_Params_List is a list of VmDaemon_killGrain_Params.
type VmDaemon_killGrain_Params_List = capnp.StructList[VmDaemon_killGrain_Params]

// NewVmDaemon_killGrain_Params creates a new list of VmDaemon_killGrain_Params.
func NewVmDaemon_killGrain_Params_List(s *capnp.Segment, sz int32) (VmDaemon_killGrain_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[VmDaemon_killGrain_Params](l), err
}

// VmDaemon_killGrain_Params_Future is a wrapper for a VmDaemon_killGrain_Params promised by a client call.
type VmDaemon_killGrain_Params_Future struct{ *capnp.Future }

func (f VmDaemon_killGrain_Params_Future) Struct() (VmDaemon_killGrain_Params, error) {
	p, err := f.Future.Ptr()
	return VmDaemon_killGrain_Params(p.Struct()), err
}

type VmDaemon_killGrain_Results capnp.Struct

// VmDaemon_killGrain_Results_TypeID is the unique identifier for the type VmDaemon_killGrain_Results.
const VmDaemon_killGrain_Results_TypeID = 0x96a574226fb11450

func NewVmDaemon_killGrain_Results(s *capnp.Segment) (VmDaemon_killGrain_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return VmDaemon_killGrain_Results(st), err
}

func NewRootVmDaemon_killGrain_Results(s *capnp.Segment) (VmDaemon_killGrain_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return VmDaemon_killGrain_Results(st), err
}

func ReadRootVmDaemon_killGrain_Results(msg *capnp.Message) (VmDaemon_killGrain_Results, error) {
	root, err := msg.Root()
	return VmDaemon_killGrain_Results(root.Struct()), err
}

func (s VmDaemon_killGrain_Results) String() string {
	str, _ := text.Marshal(0x96a574226fb11450, capnp.Struct(s))
	return str
}

func (s VmDaemon_killGrain_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VmDaemon_killGrain_Results) DecodeFromPtr(p capnp.Ptr) VmDaemon_killGrain_Results {
	return VmDaemon_killGrain_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VmDaemon_killGrain_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VmDaemon_killGrain_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VmDaemon_killGrain_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VmDaemon_killGrain_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// VmDaemon_killGrain_Results_List is a list of VmDaemon_killGrain_Results.
type VmDaemon_killGrain_Results_List = capnp.StructList[VmDaemon_killGrain_Results]

// NewVmDaemon_killGrain_Results creates a new list of VmDaemon_killGrain_Results.
func NewVmDaemon_killGrain_Results_List(s *capnp.Segment, sz int32) (VmDaemon_killGrain_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[VmDaemon_killGrain_Results](l), err
}

// VmDaemon_killGrain_Results_Future is a wrapper for a VmDaemon_killGrain_Results promised by a client call.
type VmDaemon_killGrain_Results_Future struct{ *capnp.Future }

func (f VmDaemon_killGrain_Results_Future) Struct() (VmDaemon_killGrain_Results, error) {
	p, err := f.Future.Ptr()
	return VmDaemon_killGrain_Results(p.Struct()), err
}

type VmDaemon_listGrains_Params capnp.Struct

// VmDaemon_listGrains_Params_TypeID is the unique identifier for the type VmDaemon_listGrains_Params.
const VmDaemon_listGrains_Params_TypeID = 0xb75fc37629f03a86

func NewVmDaemon_listGrains_Params(s *capnp.Segment) (VmDaemon_listGrains_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return VmDaemon_listGrains_Params(st), err
}

func NewRootVmDaemon_listGrains_Params(s *capnp.Segment) (VmDaemon_listGrains_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return VmDaemon_listGrains_Params(st), err
}

func ReadRootVmDaemon_listGrains_Params(msg *capnp.Message) (VmDaemon_listGrains_Params, error) {
	root, err := msg.Root()
	return VmDaemon_listGrains_Params(root.Struct()), err
}

func (s VmDaemon_listGrains_Params) String() string {
	str, _ := text.Marshal(0xb75fc37629f03a86, capnp.Struct(s))
	return str
}

func (s VmDaemon_listGrains_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VmDaemon_listGrains_Params) DecodeFromPtr(p capnp.Ptr) VmDaemon_listGrains_Params {
	return VmDaemon_listGrains_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VmDaemon_listGrains_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VmDaemon_listGrains_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VmDaemon_listGrains_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VmDaemon_listGrains_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// VmDaemon_listGrains_Params_List is a list of VmDaemon_listGrains_Params.
type VmDaemon_listGrains_Params_List = capnp.StructList[VmDaemon_listGrains_Params]

// NewVmDaemon_listGrains_Params creates a new list of VmDaemon_listGrains_Params.
func NewVmDaemon_listGrains_Params_List(s *capnp.Segment, sz int32) (VmDaemon_listGrains_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[VmDaemon_listGrains_Params](l), err
}

// VmDaemon_listGrains_Params_Future is a wrapper for a VmDaemon_listGrains_Params promised by a client call.
type VmDaemon_listGrains_Params_Future struct{ *capnp.Future }

func (f VmDaemon_listGrains_Params_Future) Struct() (VmDaemon_listGrains_Params, error) {
	p, err := f.Future.Ptr()
	return VmDaemon_listGrains_Params(p.Struct()), err
}

type VmDaemon_listGrains_Results capnp.Struct

// VmDaemon_listGrains_Results_TypeID is the unique identifier for the type VmDaemon_listGrains_Results.
const VmDaemon_listGrains_Results_TypeID = 0xa1e88aaeaf175e70

func NewVmDaemon_listGrains_Results(s *capnp.Segment) (VmDaemon_listGrains_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VmDaemon_listGrains_Results(st), err
}

func NewRootVmDaemon_listGrains_Results(s *capnp.Segment) (VmDaemon_listGrains_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return VmDaemon_listGrains_Results(st), err
}

func ReadRootVmDaemon_listGrains_Results(msg *capnp.Message) (VmDaemon_listGrains_Results, error) {
	root, err := msg.Root()
	return VmDaemon_listGrains_Results(root.Struct()), err
}

func (s VmDaemon_listGrains_Results) String() string {
	str, _ := text.Marshal(0xa1e88aaeaf175e70, capnp.Struct(s))
	return str
}

func (s VmDaemon_listGrains_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VmDaemon_listGrains_Results) DecodeFromPtr(p capnp.Ptr) VmDaemon_listGrains_Results {
	return VmDaemon_listGrains_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VmDaemon_listGrains_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VmDaemon_listGrains_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VmDaemon_listGrains_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VmDaemon_listGrains_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VmDaemon_listGrains_Results) Grains() (GrainInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return GrainInfo_List(p.List()), err
}

func (s VmDaemon_listGrains_Results) HasGrains() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s VmDaemon_listGrains_Results) SetGrains(v GrainInfo_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewGrains sets the grains field to a newly
// allocated GrainInfo_List, preferring placement in s's segment.
func (s VmDaemon_listGrains_Results) NewGrains(n int32) (GrainInfo_List, error) {
	l, err := NewGrainInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return GrainInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// VmDaemon_listGrains_Results_List is a list of VmDaemon_listGrains_Results.
type VmDaemon_listGrains_Results_List = capnp.StructList[VmDaemon_listGrains_Results]

// NewVmDaemon_listGrains_Results creates a new list of VmDaemon_listGrains_Results.
func NewVmDaemon_listGrains_Results_List(s *capnp.Segment, sz int32) (VmDaemon_listGrains_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[VmDaemon_listGrains_Results](l), err
}

// VmDaemon_listGrains_Results_Future is a wrapper for a VmDaemon_listGrains_Results promised by a client call.
type VmDaemon_listGrains_Results_Future struct{ *capnp.Future }

func (f VmDaemon_listGrains_Results_Future) Struct() (VmDaemon_listGrains_Results, error) {
	p, err := f.Future.Ptr()
	return VmDaemon_listGrains_Results(p.Struct()), err
}

type GrainInfo capnp.Struct

// GrainInfo_TypeID is the unique identifier for the type GrainInfo.
const GrainInfo_TypeID = 0xd996963fdc356484

func NewGrainInfo(s *capnp.Segment) (GrainInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GrainInfo(st), err
}

func NewRootGrainInfo(s *capnp.Segment) (GrainInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GrainInfo(st), err
}

func ReadRootGrainInfo(msg *capnp.Message) (GrainInfo, error) {
	root, err := msg.Root()
	return GrainInfo(root.Struct()), err
}

func (s GrainInfo) String() string {
	str, _ := text.Marshal(0xd996963fdc356484, capnp.Struct(s))
	return str
}

func (s GrainInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GrainInfo) DecodeFromPtr(p capnp.Ptr) GrainInfo {
	return GrainInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GrainInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GrainInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GrainInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GrainInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GrainInfo) GrainId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s GrainInfo) HasGrainId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GrainInfo) GrainIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s GrainInfo) SetGrainId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s GrainInfo) PackageId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s GrainInfo) HasPackageId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s GrainInfo) PackageIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s GrainInfo) SetPackageId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s GrainInfo) VsockPort() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s GrainInfo) SetVsockPort(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s GrainInfo) Pid() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s GrainInfo) SetPid(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

// GrainInfo_List is a list of GrainInfo.
type GrainInfo_List = capnp.StructList[GrainInfo]

// NewGrainInfo creates a new list of GrainInfo.
func NewGrainInfo_List(s *capnp.Segment, sz int32) (GrainInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[GrainInfo](l), err
}

// GrainInfo_Future is a wrapper for a GrainInfo promised by a client call.
type GrainInfo_Future struct{ *capnp.Future }

func (f GrainInfo_Future) Struct() (GrainInfo, error) {
	p, err := f.Future.Ptr()
	return GrainInfo(p.Struct()), err
}

const schema_d72118c15ecda7a8 = "x\xda\x8c\x93OhSY\x18\xc5\xcf\xb9\xf7e\xd2E" +
	":\xed\xe5\x05\x9amKa\xe8\xc0t:\xcct\x16\x85" +
	"\xa1e\xa8\xd4\x88Bn\x10\x17E\xaa\x8f&\xd6G\x93" +
	"\x97G^Z]\x08\xa5\xd2v\xe1\xae\x0b\x0b]\xb8p" +
	"!\x8a\x88\xc5\x95n\xeb\x1fD\xa1+\x17Z\xe9NE" +
	"7\x82\xe0F\x17\xf2\xe4\xbe\xe4\xbd\x86\x12\x8b\xbb\xdc\xfb" +
	"}\xdf9\xbf\xef\xe4\xbe\x91eNX\x7fu\xfffA" +
	"\xe8\x91\xd4/\xe1\xd2[w\xf0\x9f\x17{\xabP=2" +
	"\xbcusgf;\xd7\xff\x12\xa0\xfd\x95\x0fm\x8a4" +
	"`\x7f\xe3S{\xd9\xfc\x0aW^\xdb\x97\xdf<\xf9r" +
	"\x15:G\x02V\x1a\xf8\xdb\x15\xd3\x04\xed\x051\x0e\x86" +
	"\x85\xec\xbd\xda@\xe3\xc6\x06T.\xaeo\x8a\"a\x85" +
	"\xfeL\xdf\xd6\xdd+\x1f\xae7+)\x9a\xd2jst" +
	"=\x1a\xed\xdb\xba\xbd\xf6o\xe5\xf3\x9d\xf6\x86mq\xcc" +
	"4\xecD\x0dkc\x9f\x86\x16\x1f\x9d\xb9\xdf\xa6\xfd\xb1" +
	"\xa9\xfd\xecO\xf5\xf8\xc1\xd9\xbdW\xadQiJ\xbb\xa6" +
	"D\xfb\x9d\xd8\x02\xc3\x95\xd2\xe8\xde\xf8\xc6\xc6.t\x0f" +
	"\xb9\xbfe*Zo]>\xb7\xaf\x99\x19{S\xbe\xc7" +
	"\x1f\xe1b\xb5\xe4\x94\xab5O\x0c\xcf:\xbe\xe7\x8f\x9d" +
	"\xaaNFg\x14H\x9d\x91) 1d\x1c\x88\xd2\xd3" +
	"\x10*\x9f\xe6\xfe\x1e\x8c\xb3P\xff\x15!\xd4h\x9a\"" +
	"Y\x81q\x1aj\xc8\xcc\xf5\xa7\xc3\xc0w.xSu" +
	"\x07\xd2\xf5&\x18\xce\xbb\x95\xcaT\xddqAs\xaa\xb8" +
	"A#:I/\x98`\x81L\x18\xad\x03\x8c\xc3\xb1\x8e" +
	"\xeb\x0d\x16\xcb\xc1BE6\x02mI\x0b\xb0\x08\xa8\xee" +
	"\"\xa03\x92:'\x18.\x06\xb5\xd9\xf9B\xad\x0e6" +
	"\xd8\x05\xc1.\x1c\xa2\x1b\x03\xb5d\x1b\x0c~\xdc\x1b\xe3" +
	"zAG\x861@wI\xeaA\xc1\xf1\xb9\xa8\x8d\xbf" +
	"\x82\x05I\xf6\xee\xffQ\xa0\xb9\xfc\x19\x9e\x82Sw\xaa" +
	"\x01\xd0n\xf1\x7f\xcb\"+\xb8\x14Y\xe4K\xcc@0" +
	"s\x98d\x1bv\xa4y\xd8\x8am1\xb7zu&\xb1" +
	"?bR\x9e\x94\xd4\x05AEf\xcd\xa7\xa2N\x18\xa6" +
	"\xa3\x92\xfa\xa4\xa0\x12\"K\x01(\xfd;\xa0\x8fK\xea" +
	"\xf3\x82\xa1\xef\xcc\xce;s\xe5<\x98\xc0\x1e\x84\xefq" +
	"\xeasIZ\xe6\xae=\xa3\xf8\xbdFXy\xef\\\x0d" +
	"\xd1\x8b\xedM\xb8\x1c\x83p\xba\xe9\x96p\x95\x0dlI" +
	"R\xfb\x82laU\xcd]ER_\x14T\x92YJ" +
	"@-\x0c\x00\xda\x97\xd4\x97:\x84\xda\x81\xbd\xd3\xfbJ" +
	"\xfbn\x89\x16\x04-\xf0{\x00\x00\x00\xff\xff\xe2\x895" +
	"3"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d72118c15ecda7a8,
		Nodes: []uint64{
			0x85dcd3342469e47f,
			0x95f8c5e38213da84,
			0x96a574226fb11450,
			0xa1e88aaeaf175e70,
			0xacf36c3686aaaf17,
			0xb75fc37629f03a86,
			0xd8dc60b8c4112fc9,
			0xd996963fdc356484,
		},
		Compressed: true,
	})
}
