// Code generated by capnpc-go. DO NOT EDIT.

package settings

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	schema "capnproto.org/go/capnp/v3/std/capnp/schema"
)

// Constants defined in settings.capnp.
var (
	AdminSettings = Setting_List(capnp.MustUnmarshalRoot(x_df25727aa20cb09f[0:1520]).List())
)

type Setting capnp.Struct

// Setting_TypeID is the unique identifier for the type Setting.
const Setting_TypeID = 0xdaf29db89a9e64ef

func NewSetting(s *capnp.Segment) (Setting, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return Setting(st), err
}

func NewRootSetting(s *capnp.Segment) (Setting, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return Setting(st), err
}

func ReadRootSetting(msg *capnp.Message) (Setting, error) {
	root, err := msg.Root()
	return Setting(root.Struct()), err
}

func (s Setting) String() string {
	str, _ := text.Marshal(0xdaf29db89a9e64ef, capnp.Struct(s))
	return str
}

func (s Setting) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Setting) DecodeFromPtr(p capnp.Ptr) Setting {
	return Setting(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Setting) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Setting) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Setting) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Setting) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Setting) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Setting) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Setting) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Setting) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Setting) Type() (schema.Type, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return schema.Type(p.Struct()), err
}

func (s Setting) HasType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Setting) SetType(v schema.Type) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewType sets the type field to a newly
// allocated schema.Type struct, preferring placement in s's segment.
func (s Setting) NewType() (schema.Type, error) {
	ss, err := schema.NewType(capnp.Struct(s).Segment())
	if err != nil {
		return schema.Type{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Setting) Default() (schema.Value, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return schema.Value(p.Struct()), err
}

func (s Setting) HasDefault() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Setting) SetDefault(v schema.Value) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewDefault sets the default field to a newly
// allocated schema.Value struct, preferring placement in s's segment.
func (s Setting) NewDefault() (schema.Value, error) {
	ss, err := schema.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return schema.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Setting_List is a list of Setting.
type Setting_List = capnp.StructList[Setting]

// NewSetting creates a new list of Setting.
func NewSetting_List(s *capnp.Segment, sz int32) (Setting_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[Setting](l), err
}

// Setting_Future is a wrapper for a Setting promised by a client call.
type Setting_Future struct{ *capnp.Future }

func (f Setting_Future) Struct() (Setting, error) {
	p, err := f.Future.Ptr()
	return Setting(p.Struct()), err
}
func (p Setting_Future) Type() schema.Type_Future {
	return schema.Type_Future{Future: p.Future.Field(1, nil)}
}
func (p Setting_Future) Default() schema.Value_Future {
	return schema.Value_Future{Future: p.Future.Field(2, nil)}
}

const schema_df25727aa20cb09f = "x\xdad\x93Kh;U\x18\xc5\xbfso\x9an\xa2" +
	"\xc9\x98\xae\x04\xa9\xf8\xd8\x14\xe9\xcb*Z\x84v\x92\xdc" +
	"\x92\xb1\x99\xcc\xcc\xbd\x93j\x8b0\x0eM\xd4B\xf3 " +
	"\x99\x82-\x82P\x10\xc4\x9dE\\\xb4\xd4\x82+qc" +
	"\x17.DW\xee\x14Dj7>P\xb4\xa0\xd0\x8aR" +
	"\x10\x05\x05a\xfe\xdcLhR\xfe\xbbs~\xe7\xdc\xef" +
	"\x9b\x19\xee\xcc\x82-\xa7\xe6\xee\xb9\x1e'\xe6\xbd0\x96" +
	"\x8e?[y\xe4\xff\xb7\x9e<z\x97\x8cl*>9" +
	"\xcd\xbc\xbf\xd7}\xf4g\"\xe4\x7f\xe2\xbf\xe7\xaf\xf88" +
	"\x91\xfa\x95s\xc8\x14\x03Q|]\x7f\xef\xf0\x93\xe3\xbf" +
	"~ #\x8ba{L\xd7\xf2\x17\xe9O\xf3Wi\xad" +
	"~K\x7fD\x97q\xaf\x11E[\xad\x97{lz3" +
	"\xec\xb4:\x8ba\xbd\xb9\xd5R\x8d(\xcaj\xea\x02\xb8" +
	"\x97\xe0r 7\x1cK\x1a\xd2\x1cN`\x96\xb8\xf1\xe5" +
	"\xa1w\xc6Ad|\x7f\xe0\xfd\xd2\x17W\x1b\xde\x1f}" +
	"\xf1\xcf\xb3\xde\xbf\x1c*\x05\x86\xfc\x03\x90\xeaAp\xa8" +
	"\xc7\xb4{\x1a\x1b\xea\x19\xed\xca\xda\xd5\xb0\xaf\x9e\x87>" +
	"\x92\x0f\xb1\xa7\xea\x89lB\xaaN\"w!\xd5k\x89" +
	"|\x03]\xf5f\"\xdfFW\xbd\x93\xc8c\x9c\xab\x0f" +
	"\xf4\xbc\x8f\xf5\xbc\xcfq\xa0\xbeH\x82op\xa0\xbeK" +
	"\xe4\x05>T\x97\xba\xf3\xb7\xee\x80\xed\xab\x14\xe3P9" +
	"\xc6\x10\x9bE[\x04%KB\x14}G\xae\x075." +
	"+\xc8\x10\x1b\x04U\x85\xc0\x95\x8e\xb5V\x12\x90C." +
	"l\x93\xb8\x95\x14\x0b\xa6\x12AMV\x88H{d\x88" +
	"\x0c\x9c\xc7\xafDQgqff\x9b\xb57\xc3\xed\xe9" +
	"^\xd8\xaa\xf7\xa2v\xb79\xbd\x85v\\\xf6}7p" +
	"\x1dI\xf0\x87G\xee\xe7O\xcd\xf6\x13\x15\xb8\x0eq9" +
	"\x12=4\xbe\xb0\xf0\xf8 +\x0aH?X\xb1*\xa2" +
	"\xbfn@W\x05-\xad\xf7i\x1f*\xdbw\x83\xb2\xa3" +
	"\x06\x0b\x12?\\\x98\xf8\x9a\x124)\xab\xa6=r\xc6" +
	"5\x15M\xaa\xe7\x1cY\xea3_\xd8\xaeP~\xc0\x8a" +
	"N\xd57\xad\xaa\x90A\xc1,\xae\x8a*J\xc3\xa7\x9b" +
	"\xca\x86;Q\xfb\xa6\x8b5;X\x15\xb2*P\xb95" +
	"Cs\xabj\xf9\x12\xa5\xbb\xb8-lGf\xd7\x03\xbb" +
	"0\xfa\xd2O\xcc\xcd\xdfj\x15\xdd\x9a\x1a\xf9\xc6\xf7a" +
	"\xfe\xe6\x16cp\x8b\xd5R\x02\\\xc0\xcb\xf0\x14QJ" +
	"_G1E\xe4-sx\x15\x06\x03\x98\x80\x86\x96\x86" +
	"%\x0e\xcfe0\x18\x9b\x00#2\xec\x02\x91W\xe6\xf0" +
	"|\x86l+l6\x06\xeb\x90\x8dv;\x0d\xe4\xe2\x17" +
	"\xbf\xfa\xef\xe2\xcfW{g\xfa_\xc8\x11^\xaf7^" +
	"\x0aw\xb6#\xe4\xe2\xa3\xcc\xe9\xb7\xe7?>\xfc\xf5 " +
	"\xb9\x13\x00\x00\xff\xffO\xb3\xef."

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_df25727aa20cb09f,
		Nodes: []uint64{
			0x969b368afc2446bb,
			0xdaf29db89a9e64ef,
		},
		Compressed: true,
	})
}

var x_df25727aa20cb09f = []byte{
	0, 0, 0, 0, 189, 0, 0, 0,
	1, 0, 0, 0, 159, 1, 0, 0,
	68, 0, 0, 0, 0, 0, 3, 0,
	201, 0, 0, 0, 154, 0, 0, 0,
	208, 0, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	217, 0, 0, 0, 146, 0, 0, 0,
	224, 0, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	233, 0, 0, 0, 90, 0, 0, 0,
	236, 0, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	245, 0, 0, 0, 74, 0, 0, 0,
	248, 0, 0, 0, 3, 0, 1, 0,
	4, 1, 0, 0, 2, 0, 1, 0,
	29, 1, 0, 0, 82, 0, 0, 0,
	32, 1, 0, 0, 3, 0, 1, 0,
	44, 1, 0, 0, 2, 0, 1, 0,
	57, 1, 0, 0, 90, 0, 0, 0,
	60, 1, 0, 0, 3, 0, 1, 0,
	72, 1, 0, 0, 2, 0, 1, 0,
	85, 1, 0, 0, 130, 0, 0, 0,
	88, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	97, 1, 0, 0, 122, 0, 0, 0,
	100, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	109, 1, 0, 0, 82, 0, 0, 0,
	112, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	121, 1, 0, 0, 82, 0, 0, 0,
	124, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	133, 1, 0, 0, 114, 0, 0, 0,
	136, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	145, 1, 0, 0, 114, 0, 0, 0,
	148, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	157, 1, 0, 0, 210, 0, 0, 0,
	168, 1, 0, 0, 3, 0, 1, 0,
	180, 1, 0, 0, 2, 0, 1, 0,
	193, 1, 0, 0, 146, 0, 0, 0,
	200, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	209, 1, 0, 0, 146, 0, 0, 0,
	216, 1, 0, 0, 3, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	225, 1, 0, 0, 170, 0, 0, 0,
	232, 1, 0, 0, 3, 0, 1, 0,
	244, 1, 0, 0, 2, 0, 1, 0,
	1, 2, 0, 0, 130, 0, 0, 0,
	4, 2, 0, 0, 3, 0, 1, 0,
	16, 2, 0, 0, 2, 0, 1, 0,
	65, 67, 77, 69, 95, 68, 73, 82,
	69, 67, 84, 79, 82, 89, 95, 85,
	82, 76, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	65, 67, 77, 69, 95, 68, 78, 83,
	95, 80, 82, 79, 73, 86, 68, 69,
	82, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	65, 67, 77, 69, 95, 69, 77, 65,
	73, 76, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	66, 65, 83, 69, 95, 85, 82, 76,
	0, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 210, 0, 0, 0,
	104, 116, 116, 112, 58, 47, 47, 108,
	111, 99, 97, 108, 46, 115, 97, 110,
	100, 115, 116, 111, 114, 109, 46, 105,
	111, 0, 0, 0, 0, 0, 0, 0,
	72, 84, 84, 80, 95, 80, 79, 82,
	84, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 26, 0, 0, 0,
	56, 48, 0, 0, 0, 0, 0, 0,
	72, 84, 84, 80, 83, 95, 80, 79,
	82, 84, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 34, 0, 0, 0,
	52, 52, 51, 0, 0, 0, 0, 0,
	72, 84, 84, 80, 83, 95, 67, 69,
	82, 84, 95, 70, 73, 76, 69, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	72, 84, 84, 80, 83, 95, 75, 69,
	89, 95, 70, 73, 76, 69, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	83, 77, 84, 80, 95, 72, 79, 83,
	84, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	83, 77, 84, 80, 95, 80, 79, 82,
	84, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	83, 77, 84, 80, 95, 85, 83, 69,
	82, 78, 65, 77, 69, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	83, 77, 84, 80, 95, 80, 65, 83,
	83, 87, 79, 82, 68, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	84, 69, 77, 80, 69, 83, 84, 95,
	67, 79, 78, 84, 65, 73, 78, 69,
	82, 95, 66, 65, 67, 75, 69, 78,
	68, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 42, 0, 0, 0,
	97, 117, 116, 111, 0, 0, 0, 0,
	84, 69, 77, 80, 69, 83, 84, 95,
	86, 77, 95, 75, 69, 82, 78, 69,
	76, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	84, 69, 77, 80, 69, 83, 84, 95,
	86, 77, 95, 73, 78, 73, 84, 82,
	68, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	84, 69, 77, 80, 69, 83, 84, 95,
	86, 77, 95, 77, 69, 77, 79, 82,
	89, 95, 77, 66, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 34, 0, 0, 0,
	53, 49, 50, 0, 0, 0, 0, 0,
	84, 69, 77, 80, 69, 83, 84, 95,
	86, 77, 95, 67, 80, 85, 83, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	12, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 18, 0, 0, 0,
	50, 0, 0, 0, 0, 0, 0, 0,
}
